### PR TITLE
BL-570 feature/Update API docs

### PR DESCRIPTION
**Pull request by attaris978**
## Description

Updated API docs to reflect stakeholder-requested ability to filter using multiple selections from several search categories. Removed deprecated schema/query parameters (race/ethnicity, caseID). Added explanatory comments and notes on implementation.

Update: modifications requested by **Eric Lambert** and **William Kim** necessitated a revamping of structuring. This is now concluded and the .yaml document now matches specifications.

#### Video Link

https://www.loom.com/share/e1a02ddcd9a54a829b9cede1ed28de66

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-570?atlOrigin=eyJpIjoiNmY5Yjk0YmMzNGQ3NDU2NWEzMmI0OWEzNjhkNGQxZjAiLCJwIjoiaiJ9

## Checklist: 

- [ ✅ ] My design/diagram follows the style guidelines of this project
- [ ✅ ] My docs are organized within an appropriate folder structure in our repo
- [ ✅ ] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by vbrambila2 — APPROVED** [review]
great job on figuring out the issues with the API, I think the solutions are solid

**Comment by willkim76** [comment]
As it currently stands from the perspective of the BE team, the API documentation is accurate in terms of the query parameters. However, the API document is ahead in terms of the entity schema. Once BE team flushes out the refactor/redesign, the API Documentation will be updated accordingly, need be.

**Comment by EricMarshallLambert** [comment]
Ryan, I cannot review this. I can only leave comments. 

This has happened on other PRs I was assigned to as a reviewer as well.

**Comment by EricMarshallLambert** [comment]
I appears I do not have write access. Is that something that can be remedied?

**Review by EricMarshallLambert — CHANGES_REQUESTED** [review]
If we are passing a query parameter of comma-delimited list as a string the schema needs to be changed to type string. Update according to open API documentation.

https://swagger.io/docs/specification/data-models/data-types/#array

**Review by willkim76 — CHANGES_REQUESTED** [review]
Remember to reference OpenAPI/Swagger schema specifications for declared array types.

**Review by EricMarshallLambert — APPROVED** [review]

**Review by willkim76 — APPROVED** [review]

**Review by EricMarshallLambert — APPROVED** [review]
Thank you for updating the schema type to reflect the data, and working through this as well.

**Pull request merged**
