### PR TITLE
Bl 59 Added API Contracts

### PR DESCRIPTION
**Pull request by Jay-W03**
Co-authored-by: Uma Sitaraman
Co-authored-by: Jayda Wade
Co-authored-by: Dionis Estrella
Co-authored-by: Xavier Twitty

## Description

Added API Documentation yaml file using Swagger

#### Video Link

https://www.loom.com/share/34345e3ece69490bb505f11f4b579866

#### Jira Link

https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/8?modal=detail&selectedIssue=BL-59

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by jmthompson-dev — APPROVED** [review]
I think this look great. I really like how in depth your loom video explains the API contracts. This commit definitely contains the relevant work in accordance with the description. Good job!

**Review by billydean — APPROVED** [review]
Looks good to me. The loom video was a great guide--you'll have to teach me how you make it look so easy!

**Review by VWashingtonCoder — APPROVED** [review]
Very in-depth overview of the API to be built. As a front-end web student, it should be very simple to attach routes based on this layout.

**Review by vbrambila2 — APPROVED** [review]
Great layout of the api, thank you for bringing it to life visually.

**Comment by daslater** [comment]
Great job on this. The API is very clear and well explained. One thing that occurred to me though... I think users would be more interested in filtering for a date range rather than a specific date, particularly for the completion date. It might be a good idea to have a start date and end date for completion.

**Review by jordanc2 — APPROVED** [review]
Great job. The contract looks thorough and clearly laid out. Also, good idea, to give the stakeholder an option with the hash-key for the get-by id request!

**Comment by EstrellaDionis** [comment]
Nice and clean layout of information, endpoints and great explanation of everything in your video.

**Pull request merged**
