### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by attaris978**
## Description

This is the set of proposed data displays for the landing page, intended to limit activity with the API and to present useful information for the standard user.

#### Video Link

https://www.loom.com/share/cfaf9922789a4584b041b6034ca112ed

#### Figma Link

https://www.figma.com/file/v0VJqPfWN1hBPkynPRWMuL/BL-584-Proposal-for-Asylum-Stakeholder?node-id=0%3A1

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-584?atlOrigin=eyJpIjoiMjkyZmU0ZWJkZjEwNDMzNzllOWI2MDgyZjMyMzIzMzUiLCJwIjoiaiJ9

## Checklist:

- [ ✅ ] My design/diagram follows the style guidelines of this project
- [ ✅ ] My docs are organized within an appropriate folder structure in our repo
- [ ✅ ] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by billydean — APPROVED** [review]
Loom was easy to follow, and I like what y'all have designed. I'm approving these changes, but I do have a quick question for clarification. Ryan refers to these displays as "the landing page," but I'm not sure how that squares with the current UI mock up (at least the most recent figma(s) I have access to). 

I'm just thinking of the negative space created by the triangular arrangement. Outside the purview of this particular ticket, but I thought I'd mention it! Wasn't sure whether this was intended as a mock up _of_ the landing page or of the landing page's contents (layout-agnostic).

**Review by Joshmclemore — APPROVED** [review]
Great presentation yesterday on this. I think this is a much better idea for the landing page (especially considering mobile users). I am also curious about the negative space, but I feel like we could fix that with one design for desktop (maybe a maximized y-axis) and another for mobile (Maybe an inline with a toggle below visualization 2 and above 3. Just thoughts) when it comes to implementation. This is a vast improvement, though, and I say we go for it.

**Review by MaxwellChrist — APPROVED** [review]
As we're working on tickets to actually build out the website, we needed someone with initiative to create/explore ideas for a good landing page. The comments left before mine are asking good questions, and I'm leaning towards the latter part of what Billy commented. Rearranging these into components stacked on top of one another seems to go with the mock ups and what would make it viable for mobile users to experience as well. We needed to get the ball rolling on ideas for the landing page and this is a fantastic proposal

**Comment by VWashingtonCoder** [comment]
I am approving these changes on the basis that I do like this design as a starter for the landing page, As mentioned in the comments above, the negative blank space is throwing things off. Possibly look into maybe stretching the top chart to the width of both of the two on the bottom. 

However, as a start design, this is a very good callback to the original site's graph views. With responsive design, we could even work on the views changing based on the device views and this one will be a great inspiration to go further with the vision of the product.

**Review by VWashingtonCoder — APPROVED** [review]
I am approving these changes on the basis that I do like this design as a starter for the landing page, As mentioned in the comments above, the negative blank space is throwing things off. Possibly look into maybe stretching the top chart to the width of both of the two on the bottom. 

However, as a start design, this is a very good callback to the original site's graph views. With responsive design, we could even work on the views changing based on the device views and this one will be a great inspiration to go further with the vision of the product.

**Review by EricMarshallLambert — APPROVED** [review]
I agree with the other approvals. Great presentation last week. It makes for a more robust landing page. 

I assumed it wasn't going to be the final view of the landing page, and just a mechanism for you to display all the ideas on one screen. If that is not true I do agree that they should be vertically inline. Alternately, you could have just one summary that toggles between all the different types. I defiantly like the toggle feature you proposed on the bottom two charts.

**Review by XavierTwitty — APPROVED** [review]
Great ideas for different visuals for the components for the future landing page

**Review by vbrambila2 — APPROVED** [review]
I like this layout for a landing page. Seems straight forward and user friendly.

**Review by Mbravo36 — APPROVED** [review]
The graphs look great, the implementation of a toggle is a very helpful feature.

**Pull request merged**
