### PR TITLE
BL-408-design-visualization-components-for-case-outcomes

### PR DESCRIPTION
**Pull request by MaxwellChrist**
## Description

BL-408 Design visualization components for case outcomes

#### Video Link

[Loom Video](https://www.loom.com/share/f4224929f8fe4082a0d2c146324b83b0)

#### Jira Link

<blockquote class="trello-card"><a href="https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/8?modal=detail&selectedIssue=BL-408">Updated layout to fit style guide recommendations</a></blockquote>

#### Figma Link

[Figma Link](https://www.figma.com/file/GLbdPDRiCnHMP80mj3wWcz/Untitled?node-id=0%3A1)

## Checklist:

- [X] My design/diagram follows the style guidelines of this project
- [X] My docs are organized within an appropriate folder structure in our repo
- [X] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by attaris978 — COMMENTED** [review]
I would be careful with using the combination of orange and yellows/beiges. From an accessibility standpoint, I believe it's between 8-10% of males in the world suffer from either protanopia or deuteranopia -- which will render that orange color far too close to the beige/yellow.

**Comment by MaxwellChrist** [comment]
I agree with that take Ryan. Looking at it again, the colors are pretty similar and it's not really prudent to include that one design I created when we know once HRF's website is changed with the styles they want, we can go ahead and make the necessary button changes at that time

**Review by EricMarshallLambert — APPROVED** [review]
These are good options for the Stakeholders to look over. It would be nice to change the font on the visualization, but I understand the issue at hand.

It would be nice to have a different color background around the Plotly visualizations. My eyeballs prefer off white. However, it is merely a preference. I use "dark mode" on everything I can.

**Review by VWashingtonCoder — APPROVED** [review]
I agree that this design overall does give the Stakeholders options to consider. Especially concerning the colors and the text for the line graph visualization.

**Review by Ricardorouge — APPROVED** [review]
I think these look great the components look clean and easy to read which is the most important factor with something like this. great job max

**Pull request merged**
