### PR TITLE
BL-54_Added engineering architecture diagram.

### PR DESCRIPTION
**Pull request by Mattheus85**
Co-authored-by: Vincent Andre Washington kuraiokamiblaze@gmail.com
Co-authored-by: Matthew Mattheus 19mattheus85@gmail.com

## Description

___Add your PR description here, deleting this example___

#### Video Link

[Loom Video](https://www.loom.com/share/ee8598c73eb34f35b0b635585de9d77d)

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-54?atlOrigin=eyJpIjoiNGJjZDc2NTU0OTQ4NDhlNTkzMWUyMGEzNGM1ZmQ0MDgiLCJwIjoiaiJ9

(Example below):

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;JfipwNkb&#x2F;265-fix-refactor-sidebar-to-have-icons-representing-each-element-in-the-sidebar">Fix: Refactor sidebar to have icons representing each element in the sidebar</a></blockquote>

## Checklist:

- [X] My design/diagram follows the style guidelines of this project
- [X] My docs are organized within an appropriate folder structure in our repo
- [X] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Comment by Jay-W03** [comment]
Very simple flow and easy to follow for a basic understanding of how the system should look. Just make sure you fill in the blanks in the doc description and review and check everything off from the checklist.

**Comment by jmthompson-dev** [comment]
I think you and your team did a great job. It's simplistic but very detailed and really helps you see the inner workings of the project. This would make a great addition to the project documents.

**Comment by Sandvoxel** [comment]
Looks good I would have said something about okta, but we are not using auth at all anymore.

**Comment by vbrambila2** [comment]
Good job, diagram looks clean and easy to follow.

**Comment by Joshmclemore** [comment]
It looks good! Very easy to follow and contains everything necessary as far as I can tell.

**Review by Sandvoxel — APPROVED** [review]
Looks good not to much for the diagram with how simple the Api is.

**Review by jmthompson-dev — APPROVED** [review]
I think you and your team did a great job. It's simplistic but very detailed and really helps you see the inner workings of the project. This would make a great addition to the project documents.

**Review by vbrambila2 — APPROVED** [review]
Great job on the diagram, easy to follow and clean in design.

**Review by jordanc2 — APPROVED** [review]
This looks really good. Straight forward and to the point. Great job.

**Review by umasitaraman — APPROVED** [review]
Very crisp and concise diagram. Helps to understand the flow.

**Review by Jay-W03 — APPROVED** [review]
Very simple flow and easy to follow for a basic understanding of how the system should look.

**Pull request merged**
