### PR TITLE
BL 549 UX: Update Figma project with brand style guide

### PR DESCRIPTION
**Pull request by vbrambila2**
## Description

BL-549 UX: Update Figma project with brand style guide

#### Figma Link

[Figma](https://www.figma.com/file/GLbdPDRiCnHMP80mj3wWcz/Untitled?node-id=0%3A1)

#### Video Link

[Loom Video](https://www.loom.com/share/1b4e6ab85fb040afbef2f3990f1aa29c)

#### Trello Link

<blockquote class="trello-card"><a href="https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/8?modal=detail&selectedIssue=BL-549">Update: Added style guide to Figma project file</a></blockquote>

## Checklist:

- [ x ] My design/diagram follows the style guidelines of this project
- [ x ] My docs are organized within an appropriate folder structure in our repo
- [ x ] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by EricMarshallLambert — CHANGES_REQUESTED** [review]
I appreciate the fact you paired the hex codes next to the corresponding color palette visual.

It would be helpful to have a contrasting background behind the light logo colors. They almost completely blend in to the white background.

**Comment by attaris978** [comment]
Well done putting this together so quickly. I suspect this is not your first time doing this sort of design work as this is beautifully rendered. The video is easy to follow and provides simple and direct instructions of which items are to be used for what purpose. Congrats.

**Review by attaris978 — APPROVED** [review]
Well done putting this together so quickly. I suspect this is not your first time doing this sort of design work as this is beautifully rendered. The video is easy to follow and provides simple and direct instructions of which items are to be used for what purpose. Congrats.

**Review by EricMarshallLambert — APPROVED** [review]

**Comment by vbrambila2** [comment]
> I appreciate the fact you paired the hex codes next to the corresponding color palette visual.
> 
> It would be helpful to have a contrasting background behind the light logo colors. They almost completely blend in to the white background.

I updated the file to include backgrounds for every logo option. I used the secondary colors as the backgrounds to provide examples of how they might be used.

**Review by VWashingtonCoder — APPROVED** [review]
I like how detailed this style guide is. It will definitely be a great asset when it comes time to style the full site.

**Review by Ricardorouge — APPROVED** [review]
Looks great everything is organized and easy to find, only thing I suggest is when we do finally have access to where to get the fonts, add the italic, medium, medium italic, etc.. versions of the font next to them

**Pull request merged**
