### PR TITLE
BL-56 added pdf and fig for user flow diagram

### PR DESCRIPTION
**Pull request by billydean**
## Description

Added Figma and PDF for User Flow Diagram.

#### Video Link

https://www.loom.com/share/46f1539911e54d54b6b5dcaa70b6dab1

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-56?atlOrigin=eyJpIjoiZWUxZTk4MTYxMjlkNGRmOTkzMzMxZDBjYmNkZWQ5ODQiLCJwIjoiaiJ9

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Comment by VWashingtonCoder** [comment]
.Very nice-looking user flow. I believe the "No" option on the save and print needs to be labeled like the other "No" options but other than that, it seems pretty detailed and comprehensive. Great job!

**Comment by Joshmclemore** [comment]
Great job guys. I think my wireframe finally matches this flow. Seeing it all laid out, I can follow the flow, with no problems. The only difference is very minor. I put a dropdown for "Save / Print" which might represent an extra bubble on this flow, but it is effectively the same, it just declutters the page a bit. The user would click the dropdown, then click save or print.

**Comment by Sandvoxel** [comment]
I think it looks good this will be helpful with thinking of how to build the backend.

**Review by Sandvoxel — APPROVED** [review]
I think it looks good this will be helpful with thinking of how to build the backend.

**Review by jmthompson-dev — APPROVED** [review]
This really helps see the whole picture of the project. Good job. It's very easy to follow and understand.

**Review by VWashingtonCoder — APPROVED** [review]
Very nice-looking user flow. I believe the "No" option on the save and print needs to be labeled like the other "No" options but other than that, it seems pretty detailed and comprehensive. Great job!

**Review by jordanc2 — APPROVED** [review]
This looks great. Really easy to see the flow and should help when building out the backend as well.

**Review by umasitaraman — APPROVED** [review]
Great Job Guys. Very detailed and gives a clear picture of the flow. Very helpful in understanding the project flow and very helpful while building the backend.

**Review by Jay-W03 — APPROVED** [review]
Very simple and well laid out user flow diagram. Great job mapping out the user options.

**Pull request merged**
