### PR TITLE
BL-75 iterate design artifacts to include search and filter functionality

### PR DESCRIPTION
**Pull request by vbrambila2**
## Description

BL-75 Iterate design artifacts to include search and filter functionality
We replaced the search bar and dropdown buttons with actual Ant Design components to get a better understanding of what they will look like.
Year dropdown will filter between Calendar and Fiscal years,
View dropdown will filter between Spreadsheet, Heatmap, Trends Over Time and USIC Offices.
Search bar will allow users to filter specific items in the data. The result of the search will be visible on the table that is selected.

#### Video Link

[Loom Video](https://www.loom.com/share/dfae95cbd0934e7b876656dc61385581)

#### PDF Link

https://drive.google.com/file/d/1cmc4KlLggmTAWzJttq7lWpqJqHW_mwaq/view?usp=sharing

#### Figma Link

https://www.figma.com/file/QbtsElzcyp4XrUCA92W0Im/Untitled?node-id=0%3A1

#### Trello Link

<blockquote class="trello-card"><a href="https://bloomtechlabs.atlassian.net/jira/software/c/projects/BL/boards/8?modal=detail&selectedIssue=BL-75">Iterate design artifacts to include search and filter functionality</a></blockquote>

## Checklist:

- [x] My design/diagram follows the style guidelines of this project
- [x] My docs are organized within an appropriate folder structure in our repo
- [x] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by XavierTwitty — APPROVED** [review]
Design layout looks good and the search and the filter component are easy to understand.

**Comment by EstrellaDionis** [comment]
Very easy to look at and understand. The drop-downs displaying the different ways to view the data is a fantastic idea.

**Review by EstrellaDionis — APPROVED** [review]
Very easy to look at and understand. The drop-downs displaying the different ways to view the data is a great idea that reduces the likelihood of a user being overwhelmed with options.

**Review by jmthompson-dev — APPROVED** [review]
Looks great

**Review by VWashingtonCoder — DISMISSED** [review]
Hey...so  I like the design. It looks good. However, I'm not seeing where you can search/filter by the categories in the table. Maybe a drop down added for the categories to search the term by.

**Review by Jason7jl — COMMENTED** [review]
Great job

**Pull request merged**
