### PR TITLE
BL-57 added pdf and fig for wireframe

### PR DESCRIPTION
**Pull request by Joshmclemore**
Co-authored-by: Nathan Nichols  <nwnichols02@gmail.com>

## Description

Added Figma and PDF for Wireframe.

#### Video Link

[Loom Video] https://www.loom.com/share/246522acdc8243b28ae129ad7ddd756f

#### Jira Link

https://bloomtechlabs.atlassian.net/browse/BL-57

## Checklist:
- [X] My design/diagram follows the style guidelines of this project
- [X] My docs are organized within an appropriate folder structure in our repo
- [X] Pull request description clearly describes docs made & motivations for said additions

### CODE REVIEW

**Review by jordanc2 — APPROVED** [review]
Great job, this wireframe along with the user flow will be really helpful when building the backend.

**Review by umasitaraman — APPROVED** [review]
Great Job. This gives so much clarity on the look and feel of the App.

**Review by daslater — APPROVED** [review]
Nice work, the layout seems pretty intuitive.

**Review by jmthompson-dev — APPROVED** [review]
Looks very easy to use. I liked the next page feature you talked about to improve load times and user experience.

**Review by VWashingtonCoder — APPROVED** [review]
Very detailed and in-depth. I found the idea of even planning out the mobile view to be extremely useful as well. This should make a great design to easily transfer into code.

**Review by paulstgermain — CHANGES_REQUESTED** [review]
I don't see the files you mentioned adding here, and remember - we don't need to update our `pull_request_template.md` in order to fill our description when we open a PR!

Please add those files and return our PR template to its original form before we merge this PR up!

(Instead of editing the template file, simply open a PR - you'll be given the opportunity to then fill in and adjust your PR description based off the template right there on GitHub!)

**Review by vbrambila2 — APPROVED** [review]
I love the idea of checkboxes instead of a drop down menu to filter results. My only concern would be that it might make the page look busy, but I'm sure we'll find a way to make it look clean like the rest of the page.

**Review by jmthompson-dev — APPROVED** [review]
Looks very easy to use. I liked the next page feature you talked about to improve load times and user experience.

**Review by paulstgermain — APPROVED** [review]

**Pull request merged**
